In [6]:
import numpy as np

a, b, n, m = map(int, input().split())
mat = np.arange(a, b).reshape(n, m)
mat[1::2] = mat[1::2, ::-1]

print(mat)

[[ 2  3  4  5]
 [ 9  8  7  6]
 [10 11 12 13]
 [17 16 15 14]]
