In [24]:
import numpy as np


def box(matrix, num):
    rows, cols = matrix.shape
    a = np.linspace(num, num, (rows + 2) * (cols + 2)).reshape(rows + 2, cols + 2).astype(np.uint)
    a[1:rows + 1, 1:cols + 1] = matrix
    return a


In [25]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(box(matrix, 0))

[[0 0 0 0 0 0]
 [0 1 2 3 4 0]
 [0 5 6 7 8 0]
 [0 0 0 0 0 0]]
